name: Build and deploy a .NET 5 app to Azure App Service
on: [push]
env:
  AZURE_WEBAPP_NAME: 'GaDemoApi'
  AZURE_WEBAPP_PACKAGE_PATH: '.'
  DOTNET_VERSION: '5.0.x'
jobs: 
  build: 
    runs-on: windows-latest 
    steps:
      # Check out the repository
      - uses: actions/checkout@v2
      - uses: azure/login@v1 
        with: 
          creds: ${{ secrets.AZURE_CREDENTIALS }}
       
      # Setup .NET SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v1 
        with: 
          dotnet-version: ${{ env.DOTNET_VERSION }} 
       
      # Run dotnet build and publish
      - name: dotnet restore, build, and publish 
        run: | 
          dotnet restore 
          dotnet build --configuration Release 
          dotnet publish -c Release -o '$/myapp'  
           
      # Deploy to Azure Web apps 
      - name: Run Azure webapp deploy action using azure credentials
        uses: azure/webapps-deploy@v2 
        with:  
          app-name: ${{ env.AZURE_WEBAPP_NAME }} 
          package: '$/myapp' 
       
      - name: logout 
        run: | 
          az logout
